default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000

development: &development
  <<: *default
  username: root
  password: mysql
  database: todo_development
  host: 192.168.99.100

test:
  <<: *development
  database: todo_test

production:
  <<: *default
  username: <%= ENV['MYSQL_USERNAME'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  host: <%= ENV['MYSQL_HOST'] %>
